fyyur/views/pages.py
#----------------------------------------------------------------------------#
# Imports
#----------------------------------------------------------------------------#
import json
from datetime import datetime
import dateutil.parser
from babel import dates
from flask import (
  render_template, request, Response, flash, redirect, url_for, Blueprint
)
from ..app import app

import logging
from logging import Formatter, FileHandler

# from fyyur.page import create_page
from fyyur.models import Venue, Artist, ma 

    # TODO: implement any missing fields, as a database migration using Flask-Migrate

# TODO Implement Show and Artist models, and complete all model relationships and properties, as a database migration.

#----------------------------------------------------------------------------#
# Filters.
#----------------------------------------------------------------------------#

page = Blueprint('pages', __name__, template_folder='templates')

def format_datetime(value, format='medium'):
  date = dateutil.parser.parse(value)
  if format == 'full':
      format="EEEE MMMM, d, y 'at' h:mma"
  elif format == 'medium':
      format="EE MM, dd, y h:mma"
  return dates.format_datetime(date, format, locale='en')

app.jinja_env.filters['datetime'] = format_datetime

#----------------------------------------------------------------------------#
# Controllers.
#----------------------------------------------------------------------------#



@page.route('/')
def index():
  return render_template('pages/home.html')

@page.route('/venues')
def venues():
  # TODO: replace with real venues data.
  #       num_upcoming_shows should be aggregated based on number of upcoming shows per venue.
  cities = ['San Francisco', 'New York']
  # states = ['CA', 'NY']
  # venue = Venue.query.filter_by(city=cities[0], state=states[0]).all()
  # city = venue[0].city
  # state = venue[0].state

  data1 =[]
  # venue_serializer = {}
  # today = datetime(datetime.today().year, datetime.today().month, datetime.today().day, datetime.today().hour, datetime.today().minute)
  today = datetime.utcnow()

  for obj in cities:
    venue_serializer = {}
    vens = Venue.query.filter_by(city=obj).all()
    for ven in vens:
      venue_serializer['city'] = ven.city
      venue_serializer['state'] = ven.state
      venue_serializer['venues'] = [{}]
      venue_serializer['venues'][0]['id'] = ven.id
      venue_serializer['venues'][0]['name'] = ven.name
      # shows = list(filter(lambda show: show in [p for p in dir(show) if not callable(p)], venue.shows))
      shows = len( list(filter(lambda show: today > show.start_time, ven.shows)) )
      venue_serializer['venues'][0]['num_upcoming_shows'] = shows 
    data1.append(venue_serializer)
    # VenueSchema = ma.Schema.from_dict(data1)

  # data=[{
  #   "city": "San Francisco",
  #   "state": "CA",
  #   "venues": [{
  #     "id": 1,
  #     "name": "The Musical Hop",
  #     "num_upcoming_shows": 0,
  #   }, {
  #     "id": 3,
  #     "name": "Park Square Live Music & Coffee",
  #     "num_upcoming_shows": 1,
  #   }]
  # }, {
  #   "city": "New York",
  #   "state": "NY",
  #   "venues": [{
  #     "id": 2,
  #     "name": "The Dueling Pianos Bar",
  #     "num_upcoming_shows": 0,
  #   }]
  # }]
  # return render_template('pages/venues.html', areas=data);
  return render_template('pages/venues.html', areas=data1);

@page.route('/venues/search', methods=['POST'])
def search_venues():
  # TODO: implement search on artists with partial string search. Ensure it is case-insensitive.
  # seach for Hop should return "The Musical Hop".
  # search for "Music" should return "The Musical Hop" and "Park Square Live Music & Coffee"
  response={
    "count": 1,
    "data": [{
      "id": 2,
      "name": "The Dueling Pianos Bar",
      "num_upcoming_shows": 0,
    }]
  }
  return render_template('pages/search_venues.html', results=response, search_term=request.form.get('search_term', ''))

@page.route('/venues/<int:venue_id>')
def show_venue(venue_id):
  # shows the venue page with the given venue_id
  # TODO: replace with real venue data from the venues table, using venue_id
  data1={
    "id": 1,
    "name": "The Musical Hop",
    "genres": ["Jazz", "Reggae", "Swing", "Classical", "Folk"],
    "address": "1015 Folsom Street",
    "city": "San Francisco",
    "state": "CA",
    "phone": "123-123-1234",
    "website": "https://www.themusicalhop.com",
    "facebook_link": "https://www.facebook.com/TheMusicalHop",
    "seeking_talent": True,
    "seeking_description": "We are on the lookout for a local artist to play every two weeks. Please call us.",
    "image_link": "https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60",
    "past_shows": [{
      "artist_id": 4,
      "artist_name": "Guns N Petals",
      "artist_image_link": "https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80",
      "start_time": "2019-05-21T21:30:00.000Z"
    }],
    "upcoming_shows": [],
    "past_shows_count": 1,
    "upcoming_shows_count": 0,
  }
  data2={
    "id": 2,
    "name": "The Dueling Pianos Bar",
    "genres": ["Classical", "R&B", "Hip-Hop"],
    "address": "335 Delancey Street",
    "city": "New York",
    "state": "NY",
    "phone": "914-003-1132",
    "website": "https://www.theduelingpianos.com",
    "facebook_link": "https://www.facebook.com/theduelingpianos",
    "seeking_talent": False,
    "image_link": "https://images.unsplash.com/photo-1497032205916-ac775f0649ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80",
    "past_shows": [],
    "upcoming_shows": [],
    "past_shows_count": 0,
    "upcoming_shows_count": 0,
  }
  data3={
    "id": 3,
    "name": "Park Square Live Music & Coffee",
    "genres": ["Rock n Roll", "Jazz", "Classical", "Folk"],
    "address": "34 Whiskey Moore Ave",
    "city": "San Francisco",
    "state": "CA",
    "phone": "415-000-1234",
    "website": "https://www.parksquarelivemusicandcoffee.com",
    "facebook_link": "https://www.facebook.com/ParkSquareLiveMusicAndCoffee",
    "seeking_talent": False,
    "image_link": "https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80",
    "past_shows": [{
      "artist_id": 5,
      "artist_name": "Matt Quevedo",
      "artist_image_link": "https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80",
      "start_time": "2019-06-15T23:00:00.000Z"
    }],
    "upcoming_shows": [{
      "artist_id": 6,
      "artist_name": "The Wild Sax Band",
      "artist_image_link": "https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80",
      "start_time": "2035-04-01T20:00:00.000Z"
    }, {
      "artist_id": 6,
      "artist_name": "The Wild Sax Band",
      "artist_image_link": "https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80",
      "start_time": "2035-04-08T20:00:00.000Z"
    }, {
      "artist_id": 6,
      "artist_name": "The Wild Sax Band",
      "artist_image_link": "https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80",
      "start_time": "2035-04-15T20:00:00.000Z"
    }],
    "past_shows_count": 1,
    "upcoming_shows_count": 1,
  }
  data = list(filter(lambda d: d['id'] == venue_id, [data1, data2, data3]))[0]
  return render_template('pages/show_venue.html', venue=data)

#  Create Venue
#  ----------------------------------------------------------------



@page.route('/venues/create', methods=['POST'])
def create_venue_submission():
  # TODO: insert form data as a new Venue record in the db, instead
  # TODO: modify data to be the data object returned from db insertion

  # on successful db insert, flash success
  flash('Venue ' + request.form['name'] + ' was successfully listed!')
  # TODO: on unsuccessful db insert, flash an error instead.
  # e.g., flash('An error occurred. Venue ' + data.name + ' could not be listed.')
  # see: http://flask.pocoo.org/docs/1.0/patterns/flashing/
  return render_template('pages/home.html')

@page.route('/venues/<venue_id>', methods=['DELETE'])
def delete_venue(venue_id):
  # TODO: Complete this endpoint for taking a venue_id, and using
  # SQLAlchemy ORM to delete a record. Handle cases where the session commit could fail.

  # BONUS CHALLENGE: Implement a button to delete a Venue on a Venue Page, have it so that
  # clicking that button delete it from the db then redirect the user to the homepage
  return None

#  Artists
#  ----------------------------------------------------------------
@page.route('/artists')
def artists():
  # TODO: replace with real data returned from querying the database
  data=[{
    "id": 4,
    "name": "Guns N Petals",
  }, {
    "id": 5,
    "name": "Matt Quevedo",
  }, {
    "id": 6,
    "name": "The Wild Sax Band",
  }]
  return render_template('pages/artists.html', artists=data)

@page.route('/artists/search', methods=['POST'])
def search_artists():
  # TODO: implement search on artists with partial string search. Ensure it is case-insensitive.
  # seach for "A" should return "Guns N Petals", "Matt Quevado", and "The Wild Sax Band".
  # search for "band" should return "The Wild Sax Band".
  response={
    "count": 1,
    "data": [{
      "id": 4,
      "name": "Guns N Petals",
      "num_upcoming_shows": 0,
    }]
  }
  return render_template('page/search_artists.html', results=response, search_term=request.form.get('search_term', ''))

@page.route('/artists/<int:artist_id>')
def show_artist(artist_id):
  # shows the artist page with the given artist_id

fyyur/templates/forms/edit_artist.html
{% extends 'main.html' %}
{% block title %}Edit Artist{% endblock %}
{% block content %}
  <div class="form-wrapper">
    <form class="form" method="post" action="/artists/{{artist.id}}/edit">
      <h3 class="form-heading">Edit artist <em>{{ artist.name }}</em></h3>
      <div class="form-group">
        <label for="name">Name</label>
        {{ form.name(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
          <label>City & State</label>
          <div class="form-inline">
            <div class="form-group">
              {{ form.city(class_ = 'form-control', placeholder='City', autofocus = true) }}
            </div>
            <div class="form-group">
              {{ form.state(class_ = 'form-control', placeholder='State', autofocus = true) }}
            </div>
          </div>
      </div>
      <div class="form-group">
          <label for="phone">Phone</label>
          {{ form.phone(class_ = 'form-control', placeholder='xxx-xxx-xxxx', autofocus = true) }}
        </div>
      <div class="form-group">
        <label for="genres">Genres</label>
        <small>Ctrl+Click to select multiple</small>
        {{ form.genres(class_ = 'form-control', placeholder='Genres, separated by commas', autofocus = true) }}
      </div>
      <div class="form-group">
          <label for="facebook_link">Facebook Link</label>
          {{ form.facebook_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
        </div>
      
      <div class="form-group">
          <label for="image_link">Image Link</label>
          {{ form.image_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
      </div>

      <div class="form-group">
            <label for="website_link">Website Link</label>
            {{ form.website_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
      </div>

      <div class="form-group">
          <label for="seeking_venue">Looking for Venues</label>
          {{ form.seeking_venue(placeholder='Venue', autofocus = true) }}
      </div>

      <div class="form-group">
          <label for="seeking_description">Seeking Description</label>
          {{ form.seeking_description(class_ = 'form-control', autofocus = true) }}
      </div>
      
      <input type="submit" value="Edit Artist" class="btn btn-primary btn-lg btn-block">
    </form>
  </div>
{% endblock %}

fyyur/templates/forms/edit_venue.html
{% extends 'main.html' %}
{% block title %}Edit Venue{% endblock %}
{% block content %}
  <div class="form-wrapper">
    <form class="form" method="post" action="/venues/{{venue.id}}/edit">
      <h3 class="form-heading">Edit venue <em>{{ venue.name }}</em> <a href="{{ url_for('index') }}" title="Back to homepage"><i class="fa fa-home pull-right"></i></a></h3>
      <div class="form-group">
        <label for="name">Name</label>
        {{ form.name(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
          <label>City & State</label>
          <div class="form-inline">
            <div class="form-group">
              {{ form.city(class_ = 'form-control', placeholder='City', autofocus = true) }}
            </div>
            <div class="form-group">
              {{ form.state(class_ = 'form-control', placeholder='State', autofocus = true) }}
            </div>
          </div>
      </div>
      <div class="form-group">
        <label for="address">Address</label>
        {{ form.address(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
          <label for="phone">Phone</label>
          {{ form.phone(class_ = 'form-control', placeholder='xxx-xxx-xxxx', autofocus = true) }}
        </div>
      <div class="form-group">
        <label for="genres">Genres</label>
        <small>Ctrl+Click to select multiple</small>
        {{ form.genres(class_ = 'form-control', placeholder='Genres, separated by commas', autofocus = true) }}
      </div>
      <div class="form-group">
          <label for="facebook_link">Facebook Link</label>
          {{ form.facebook_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
       </div>
      
       <div class="form-group">
          <label for="image_link">Image Link</label>
          {{ form.image_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
       </div>

       <div class="form-group">
              <label for="website_link">Website Link</label>
              {{ form.website_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
        </div>

        <div class="form-group">
             <label for="seeking_talent">Looking for Talent</label>
             {{ form.seeking_talent(placeholder='Venue', autofocus = true) }}
        </div>

        <div class="form-group">
            <label for="seeking_description">Seeking Description</label>
            {{ form.seeking_description(class_ = 'form-control', autofocus = true) }}
          </div>
      
      <input type="submit" value="Edit Venue" class="btn btn-primary btn-lg btn-block">
    </form>
  </div>
{% endblock %}

fyyur/templates/forms/form.html
<!doctype html>
<head>
<meta charset="utf-8">
<title>{% block title %}{% endblock %}</title>

<!-- meta -->
<meta name="description" content="">
<meta name="author" content="">
<meta name="viewport" content="width=device-width,initial-scale=1">
<!-- /meta -->

<!-- styles -->
<link type="text/css" rel="stylesheet" href="/static/css/font-awesome-4.1.0.min.css" />
<link type="text/css" rel="stylesheet" href="/static/css/bootstrap-3.1.1.min.css">
<link type="text/css" rel="stylesheet" href="/static/css/bootstrap-theme-3.1.1.min.css" />
<link type="text/css" rel="stylesheet" href="/static/css/layout.main.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.responsive.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.quickfix.css" />
<!-- /styles -->

<!-- favicons -->
<link rel="shortcut icon" href="/static/ico/favicon.png">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="/static/ico/apple-touch-icon-57-precomposed.png">
<link rel="shortcut icon" href="/static/ico/favicon.png">
<!-- /favicons -->

<!-- scripts -->
<script src="/static/js/libs/modernizr-2.8.2.min.js"></script>
<!--[if lt IE 9]><script src="/static/js/libs/respond-1.4.2.min.js"></script><![endif]-->
<!-- /scripts -->

</head>
<body class="form-only-page">

  <div class="container">

    {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning fade in">
            <a class="close" data-dismiss="alert">&times;</a>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}

  </div>

  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script type="text/javascript" src="/static/js/libs/jquery-1.11.1.min.js"><\/script>')</script>
  <script type="text/javascript" src="/static/js/libs/bootstrap-3.1.1.min.js" defer></script>
  <script type="text/javascript" src="/static/js/plugins.js" defer></script>
  <script type="text/javascript" src="/static/js/script.js" defer></script>

</body>
</html>

fyyur/templates/forms/new_artist.html
{% extends 'main.html' %}
{% block title %}New Artist{% endblock %}
{% block content %}
  <div class="form-wrapper">
    <form method="post" class="form">
      <h3 class="form-heading">List a new artist</h3>
      <div class="form-group">
        <label for="name">Name</label>
        {{ form.name(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
          <label>City & State</label>
          <div class="form-inline">
            <div class="form-group">
              {{ form.city(class_ = 'form-control', placeholder='City', autofocus = true) }}
            </div>
            <div class="form-group">
              {{ form.state(class_ = 'form-control', placeholder='State', autofocus = true) }}
            </div>
          </div>
      </div>
      <div class="form-group">
          <label for="phone">Phone</label>
          {{ form.phone(class_ = 'form-control', placeholder='xxx-xxx-xxxx', autofocus = true) }}
        </div>
      <div class="form-group">
        <label for="genres">Genres</label>
        <small>Ctrl+Click to select multiple</small>
        {{ form.genres(class_ = 'form-control', placeholder='Genres, separated by commas', autofocus = true) }}
      </div>
      <div class="form-group">
          <label for="facebook_link">Facebook Link</label>
          {{ form.facebook_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
        </div>
      
        <div class="form-group">
          <label for="image_link">Image Link</label>
          {{ form.image_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
        </div>

        <div class="form-group">
            <label for="website_link">Website Link</label>
            {{ form.website_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
          </div>

          <div class="form-group">
              <label for="seeking_venue">Looking for Venues</label>
              {{ form.seeking_venue(placeholder='Venue', autofocus = true) }}
          </div>

          <div class="form-group">
              <label for="seeking_description">Seeking Description</label>
              {{ form.seeking_description(class_ = 'form-control', autofocus = true) }}
            </div>
      <input type="submit" value="Create Artist" class="btn btn-primary btn-lg btn-block">
    </form>
  </div>
{% endblock %}

fyyur/templates/forms/new_show.html
{% extends 'main.html' %}
{% block title %}New Show Listing{% endblock %}
{% block content %}
  <div class="form-wrapper">
    <form method="post" class="form">
      <h3 class="form-heading">List a new show</h3>
      <div class="form-group">
        <label for="artist_id">Artist ID</label>
        <small>ID can be found on the Artist's Page</small>
        {{ form.artist_id(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
        <label for="venue_id">Venue ID</label>
        <small>ID can be found on the Venue's Page</small>
        {{ form.venue_id(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
          <label for="start_time">Start Time</label>
          {{ form.start_time(class_ = 'form-control', placeholder='YYYY-MM-DD HH:MM', autofocus = true) }}
        </div>
      <input type="submit" value="Create Venue" class="btn btn-primary btn-lg btn-block">
    </form>
  </div>
{% endblock %}

fyyur/templates/forms/new_venue.html
{% extends 'main.html' %}
{% block title %}New Venue{% endblock %}
{% block content %}
  <div class="form-wrapper">
    <form method="post" class="form" action="/venues/create">
      <h3 class="form-heading">List a new venue <a href="{{ url_for('pages.index') }}" title="Back to homepage"><i class="fa fa-home pull-right"></i></a></h3>
      <div class="form-group">
        <label for="name">Name</label>
        {{ form.name(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
          <label>City & State</label>
          <div class="form-inline">
            <div class="form-group">
              {{ form.city(class_ = 'form-control', placeholder='City', autofocus = true) }}
            </div>
            <div class="form-group">
              {{ form.state(class_ = 'form-control', placeholder='State', autofocus = true) }}
            </div>
          </div>
      </div>
      <div class="form-group">
        <label for="address">Address</label>
        {{ form.address(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
          <label for="phone">Phone</label>
          {{ form.phone(class_ = 'form-control', placeholder='xxx-xxx-xxxx', autofocus = true) }}
        </div>
      <div class="form-group">
        <label for="genres">Genres</label>
        <small>Ctrl+Click to select multiple</small>
        {{ form.genres(class_ = 'form-control', placeholder='Genres, separated by commas', autofocus = true) }}
      </div>
      
      <div class="form-group">
          <label for="facebook_link">Facebook Link</label>
          {{ form.facebook_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
       </div>
      
       <div class="form-group">
          <label for="image_link">Image Link</label>
          {{ form.image_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
       </div>

       <div class="form-group">
            <label for="website_link">Website Link</label>
            {{ form.website_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
       </div>

       <div class="form-group">
             <label for="seeking_talent">Looking for Talent</label>
             {{ form.seeking_talent(placeholder='Venue', autofocus = true) }}
       </div>

       <div class="form-group">
            <label for="seeking_description">Seeking Description</label>
            {{ form.seeking_description(class_ = 'form-control', placeholder='Description', autofocus = true) }}
       </div>
      <input type="submit" value="Create Venue" class="btn btn-primary btn-lg btn-block">
    </form>
  </div>
{% endblock %}